spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/systemclean?useUnicode=true&serverTimezone=GMT-8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
server:
  port: 8443
  ssl:
    key-store: F:\schoolservices\server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: 123456
    key-store-type: JKS